currencies_list = \
    {
        "meta": {"last_updated_at": "2023-07-16T23:59:59Z"},
        "data": {
            "ADA": {"code": "ADA", "value": 3.1708748918},
            "AED": {"code": "AED", "value": 3.6730654275},
            "AFN": {"code": "AFN", "value": 85.8781281679},
            "ALL": {"code": "ALL", "value": 91.834477196},
            "AMD": {"code": "AMD", "value": 389.1186082468},
            "ANG": {"code": "ANG", "value": 1.7977513364},
            "AOA": {"code": "AOA", "value": 823.7111934278},
            "ARB": {"code": "ARB", "value": 0.7852540803},
            "ARS": {"code": "ARS", "value": 265.0734257343},
            "AUD": {"code": "AUD", "value": 1.4625151747},
            "AVAX": {"code": "AVAX", "value": 0.0698463612},
            "AWG": {"code": "AWG", "value": 1.79},
            "AZN": {"code": "AZN", "value": 1.703490172},
            "BAM": {"code": "BAM", "value": 1.7387212314},
            "BBD": {"code": "BBD", "value": 2.0140462152},
            "BDT": {"code": "BDT", "value": 108.5033767563},
            "BGN": {"code": "BGN", "value": 1.7388993069},
            "BHD": {"code": "BHD", "value": 0.3763170714},
            "BIF": {"code": "BIF", "value": 2821.9765471974},
            "BMD": {"code": "BMD", "value": 1},
            "BNB": {"code": "BNB", "value": 0.0040692486},
            "BND": {"code": "BND", "value": 1.3172422371},
            "BOB": {"code": "BOB", "value": 6.8924763748},
            "BRL": {"code": "BRL", "value": 4.7895995986},
            "BSD": {"code": "BSD", "value": 0.9974661658},
            "BTC": {"code": "BTC", "value": 3.30159e-5},
            "BTN": {"code": "BTN", "value": 81.9164416916},
            "BUSD": {"code": "BUSD", "value": 0.997703945},
            "BWP": {"code": "BWP", "value": 13.090636552},
            "BYN": {"code": "BYN", "value": 2.5178473547},
            "BYR": {"code": "BYR", "value": 19600},
            "BZD": {"code": "BZD", "value": 2.0106683988},
            "CAD": {"code": "CAD", "value": 1.3227151939},
            "CDF": {"code": "CDF", "value": 2465.0003290101},
            "CHF": {"code": "CHF", "value": 0.8620961635},
            "CLF": {"code": "CLF", "value": 0.0295180047},
            "CLP": {"code": "CLP", "value": 814.5085273056},
            "CNY": {"code": "CNY", "value": 7.1413052373},
            "COP": {"code": "COP", "value": 4059},
            "CRC": {"code": "CRC", "value": 542.6501914308},
            "CUC": {"code": "CUC", "value": 1},
            "CUP": {"code": "CUP", "value": 24},
            "CVE": {"code": "CVE", "value": 98.0219689916},
            "CZK": {"code": "CZK", "value": 21.1722047594},
            "DAI": {"code": "DAI", "value": 0.9988545543},
            "DJF": {"code": "DJF", "value": 177.6059346736},
            "DKK": {"code": "DKK", "value": 6.6356050065},
            "DOP": {"code": "DOP", "value": 55.8207852785},
            "DOT": {"code": "DOT", "value": 0.188108083},
            "DZD": {"code": "DZD", "value": 134.1903615606},
            "EGP": {"code": "EGP", "value": 30.9060219796},
            "ERN": {"code": "ERN", "value": 15.0000199412},
            "ETB": {"code": "ETB", "value": 54.9064426216},
            "ETH": {"code": "ETH", "value": 0.0005191039},
            "EUR": {"code": "EUR", "value": 0.8907151674},
            "FJD": {"code": "FJD", "value": 2.1792033363},
            "FKP": {"code": "FKP", "value": 0.7639415559},
            "GBP": {"code": "GBP", "value": 0.7639701356},
            "GEL": {"code": "GEL", "value": 2.5749854027},
            "GGP": {"code": "GGP", "value": 0.7639413282},
            "GHS": {"code": "GHS", "value": 11.3464034239},
            "GIP": {"code": "GIP", "value": 0.7639414688},
            "GMD": {"code": "GMD", "value": 59.6499042129},
            "GNF": {"code": "GNF", "value": 8576.2557423189},
            "GTQ": {"code": "GTQ", "value": 7.8277112749},
            "GYD": {"code": "GYD", "value": 209.627990057},
            "HKD": {"code": "HKD", "value": 7.8146113443},
            "HNL": {"code": "HNL", "value": 24.5517221611},
            "HRK": {"code": "HRK", "value": 6.7238602616},
            "HTG": {"code": "HTG", "value": 138.6496231232},
            "HUF": {"code": "HUF", "value": 333.0430183253},
            "IDR": {"code": "IDR", "value": 14958},
            "ILS": {"code": "ILS", "value": 3.6063756888},
            "IMP": {"code": "IMP", "value": 0.7639415805},
            "INR": {"code": "INR", "value": 82.0770643948},
            "IQD": {"code": "IQD", "value": 1306.7522464389},
            "IRR": {"code": "IRR", "value": 42275.005007893},
            "ISK": {"code": "ISK", "value": 130.8499799657},
            "JEP": {"code": "JEP", "value": 0.7639416024},
            "JMD": {"code": "JMD", "value": 154.2605862806},
            "JOD": {"code": "JOD", "value": 0.709297095},
            "JPY": {"code": "JPY", "value": 138.6965193924},
            "KES": {"code": "KES", "value": 141.450446552},
            "KGS": {"code": "KGS", "value": 87.8700735473},
            "KHR": {"code": "KHR", "value": 4116.9941509643},
            "KMF": {"code": "KMF", "value": 438.9998495698},
            "KPW": {"code": "KPW", "value": 900.0176297473},
            "KRW": {"code": "KRW", "value": 1269.3403850386},
            "KWD": {"code": "KWD", "value": 0.3062600567},
            "KYD": {"code": "KYD", "value": 0.8313111221},
            "KZT": {"code": "KZT", "value": 444.121510795},
            "LAK": {"code": "LAK", "value": 19094.993349292},
            "LBP": {"code": "LBP", "value": 14972.664683234},
            "LKR": {"code": "LKR", "value": 319.7137964334},
            "LRD": {"code": "LRD", "value": 183.6972317482},
            "LSL": {"code": "LSL", "value": 18.0450384471},
            "LTC": {"code": "LTC", "value": 0.0107515476},
            "LTL": {"code": "LTL", "value": 2.95274},
            "LVL": {"code": "LVL", "value": 0.60489},
            "LYD": {"code": "LYD", "value": 4.7401885228},
            "MAD": {"code": "MAD", "value": 9.6073263956},
            "MATIC": {"code": "MATIC", "value": 1.3004662625},
            "MDL": {"code": "MDL", "value": 17.9748433707},
            "MGA": {"code": "MGA", "value": 4505.4901288367},
            "MKD": {"code": "MKD", "value": 54.7717540419},
            "MMK": {"code": "MMK", "value": 2094.7685580893},
            "MNT": {"code": "MNT", "value": 3444.3374453824},
            "MOP": {"code": "MOP", "value": 8.0301385009},
            "MRO": {"code": "MRO", "value": 356.999828},
            "MUR": {"code": "MUR", "value": 45.3047440567},
            "MVR": {"code": "MVR", "value": 15.4102598493},
            "MWK": {"code": "MWK", "value": 1051.5181712774},
            "MXN": {"code": "MXN", "value": 16.7541817242},
            "MYR": {"code": "MYR", "value": 4.5260287801},
            "MZN": {"code": "MZN", "value": 63.2497399595},
            "NAD": {"code": "NAD", "value": 18.1599546717},
            "NGN": {"code": "NGN", "value": 776.4973834945},
            "NIO": {"code": "NIO", "value": 36.4848714301},
            "NOK": {"code": "NOK", "value": 10.0533310595},
            "NPR": {"code": "NPR", "value": 131.0663790766},
            "NZD": {"code": "NZD", "value": 1.5711701773},
            "OMR": {"code": "OMR", "value": 0.3843360463},
            "OP": {"code": "OP", "value": 0.6702701651},
            "PAB": {"code": "PAB", "value": 0.9974661719},
            "PEN": {"code": "PEN", "value": 3.5669646419},
            "PGK": {"code": "PGK", "value": 3.6111484519},
            "PHP": {"code": "PHP", "value": 54.3498342057},
            "PKR": {"code": "PKR", "value": 273.3180756876},
            "PLN": {"code": "PLN", "value": 3.9706565622},
            "PYG": {"code": "PYG", "value": 7236.5212748589},
            "QAR": {"code": "QAR", "value": 3.6410153655},
            "RON": {"code": "RON", "value": 4.3956006546},
            "RSD": {"code": "RSD", "value": 104.2592556369},
            "RUB": {"code": "RUB", "value": 90.2499532331},
            "RWF": {"code": "RWF", "value": 1164.5109773333},
            "SAR": {"code": "SAR", "value": 3.7518033932},
            "SBD": {"code": "SBD", "value": 8.3687884789},
            "SCR": {"code": "SCR", "value": 13.293983898},
            "SDG": {"code": "SDG", "value": 601.5014641498},
            "SEK": {"code": "SEK", "value": 10.2376460343},
            "SGD": {"code": "SGD", "value": 1.321485249},
            "SHP": {"code": "SHP", "value": 1.2167502282},
            "SLL": {"code": "SLL", "value": 19750.002984215},
            "SOL": {"code": "SOL", "value": 0.0364213164},
            "SOS": {"code": "SOS", "value": 568.5030032913},
            "SRD": {"code": "SRD", "value": 38.1045069798},
            "STD": {"code": "STD", "value": 20697.981008},
            "SVC": {"code": "SVC", "value": 8.7282760779},
            "SYP": {"code": "SYP", "value": 2512.532047057},
            "SZL": {"code": "SZL", "value": 17.990844819},
            "THB": {"code": "THB", "value": 34.6395386526},
            "TJS": {"code": "TJS", "value": 10.9177235379},
            "TMT": {"code": "TMT", "value": 3.5},
            "TND": {"code": "TND", "value": 3.0350056002},
            "TOP": {"code": "TOP", "value": 2.3211503279},
            "TRY": {"code": "TRY", "value": 26.2512996616},
            "TTD": {"code": "TTD", "value": 6.7724596773},
            "TWD": {"code": "TWD", "value": 30.9650193695},
            "TZS": {"code": "TZS", "value": 2446.0003097801},
            "UAH": {"code": "UAH", "value": 36.6535138637},
            "UGX": {"code": "UGX", "value": 3659.1552060973},
            "USD": {"code": "USD", "value": 1.000002526},
            "USDC": {"code": "USDC", "value": 0.9991669288},
            "USDT": {"code": "USDT", "value": 0.9975258364},
            "UYU": {"code": "UYU", "value": 38.0406342322},
            "UZS": {"code": "UZS", "value": 11549.09762404},
            "VEF": {"code": "VEF", "value": 2841983.9075773},
            "VND": {"code": "VND", "value": 23642.5},
            "VUV": {"code": "VUV", "value": 116.6866845724},
            "WST": {"code": "WST", "value": 2.687119363},
            "XAF": {"code": "XAF", "value": 583.1507581111},
            "XAG": {"code": "XAG", "value": 0.0401914837},
            "XAU": {"code": "XAU", "value": 0.0005119572},
            "XCD": {"code": "XCD", "value": 2.7025503331},
            "XDR": {"code": "XDR", "value": 0.7431210813},
            "XOF": {"code": "XOF", "value": 583.1507191357},
            "XPD": {"code": "XPD", "value": 0.0007888021},
            "XPF": {"code": "XPF", "value": 106.8499692123},
            "XPT": {"code": "XPT", "value": 0.0010294146},
            "XRP": {"code": "XRP", "value": 1.3348423214},
            "YER": {"code": "YER", "value": 250.3502197191},
            "ZAR": {"code": "ZAR", "value": 18.1154983556},
            "ZMK": {"code": "ZMK", "value": 9001.2},
            "ZMW": {"code": "ZMW", "value": 18.5535883959},
            "ZWL": {"code": "ZWL", "value": 321.999592}
                }
    }


currencies_info = \
    {'data':  {
        "AED": {"symbol": "AED", "name": "United Arab Emirates Dirham", "symbol_native": "\xd8\xaf.\xd8\xa5",
                "decimal_digits": 2, "rounding": 0, "code": "AED", "name_plural": "UAE dirhams"},
        "AFN": {"symbol": "Af", "name": "Afghan Afghani", "symbol_native": "\xd8\x8b", "decimal_digits": 0,
                "rounding": 0, "code": "AFN", "name_plural": "Afghan Afghanis"},
        "ALL": {"symbol": "ALL", "name": "Albanian Lek", "symbol_native": "Lek", "decimal_digits": 0, "rounding": 0,
                "code": "ALL", "name_plural": "Albanian lek\xc3\xab"},
        "AMD": {"symbol": "AMD", "name": "Armenian Dram", "symbol_native": "\xd5\xa4\xd6\x80.", "decimal_digits": 0,
                "rounding": 0, "code": "AMD", "name_plural": "Armenian drams"},
        "ANG": {"symbol": "\xc6\x92", "name": "NL Antillean Guilder", "symbol_native": "NA\xc6\x92",
                "decimal_digits": 2, "rounding": 0, "code": "ANG", "icon_name": "ang",
                "name_plural": "NL Antillean Guilders"},
        "AOA": {"symbol": "Kz", "name": "Angolan Kwanza", "symbol_native": "Kz", "decimal_digits": 2, "rounding": 0,
                "code": "AOA", "icon_name": "aoa", "name_plural": "Angolan Kwanza"},
        "ARS": {"symbol": "AR$", "name": "Argentine Peso", "symbol_native": "$", "decimal_digits": 2, "rounding": 0,
                "code": "ARS", "name_plural": "Argentine pesos"},
        "AUD": {"symbol": "AU$", "name": "Australian Dollar", "symbol_native": "$", "decimal_digits": 2, "rounding": 0,
                "code": "AUD", "name_plural": "Australian dollars"},
        "AWG": {"symbol": "Afl.", "name": "Aruban Florin", "symbol_native": "Afl.", "decimal_digits": 2, "rounding": 0,
                "code": "AWG", "icon_name": "awg", "name_plural": "Aruban Florin"},
        "AZN": {"symbol": "man.", "name": "Azerbaijani Manat", "symbol_native": "\xd0\xbc\xd0\xb0\xd0\xbd.",
                "decimal_digits": 2, "rounding": 0, "code": "AZN", "name_plural": "Azerbaijani manats"},
        "BAM": {"symbol": "KM", "name": "Bosnia-Herzegovina Convertible Mark", "symbol_native": "KM",
                "decimal_digits": 2, "rounding": 0, "code": "BAM",
                "name_plural": "Bosnia-Herzegovina convertible marks"},
        "BBD": {"symbol": "Bds$", "name": "Barbadian Dollar", "symbol_native": "$", "decimal_digits": 2, "rounding": 0,
                "code": "BBD", "icon_name": "bbd", "name_plural": "Barbadian Dollars"},
        "BDT": {"symbol": "Tk", "name": "Bangladeshi Taka", "symbol_native": "\xe0\xa7\xb3", "decimal_digits": 2,
                "rounding": 0, "code": "BDT", "name_plural": "Bangladeshi takas"},
        "BGN": {"symbol": "BGN", "name": "Bulgarian Lev", "symbol_native": "\xd0\xbb\xd0\xb2.", "decimal_digits": 2,
                "rounding": 0, "code": "BGN", "name_plural": "Bulgarian leva"},
        "BHD": {"symbol": "BD", "name": "Bahraini Dinar", "symbol_native": "\xd8\xaf.\xd8\xa8.\xe2\x80\x8f",
                "decimal_digits": 3, "rounding": 0, "code": "BHD", "name_plural": "Bahraini dinars"},
        "BIF": {"symbol": "FBu", "name": "Burundian Franc", "symbol_native": "FBu", "decimal_digits": 0, "rounding": 0,
                "code": "BIF", "name_plural": "Burundian francs"},
        "BMD": {"symbol": "BD$", "name": "Bermudan Dollar", "symbol_native": "$", "decimal_digits": 2, "rounding": 0,
                "code": "BMD", "icon_name": "bmd", "name_plural": "Bermudan Dollars"},
        "BND": {"symbol": "BN$", "name": "Brunei Dollar", "symbol_native": "$", "decimal_digits": 2, "rounding": 0,
                "code": "BND", "name_plural": "Brunei dollars"},
        "BOB": {"symbol": "Bs", "name": "Bolivian Boliviano", "symbol_native": "Bs", "decimal_digits": 2, "rounding": 0,
                "code": "BOB", "name_plural": "Bolivian bolivianos"},
        "BRL": {"symbol": "R$", "name": "Brazilian Real", "symbol_native": "R$", "decimal_digits": 2, "rounding": 0,
                "code": "BRL", "name_plural": "Brazilian reals"},
        "BSD": {"symbol": "B$", "name": "Bahamian Dollar", "symbol_native": "$", "decimal_digits": 2, "rounding": 0,
                "code": "BSD", "icon_name": "bsd", "name_plural": "Bahamian Dollars"},
        "BTN": {"symbol": "Nu.", "name": "Bhutanese Ngultrum", "symbol_native": "Nu.", "decimal_digits": 2,
                "rounding": 0, "code": "BTN", "icon_name": "btn", "name_plural": "Bhutanese Ngultrum"},
        "BWP": {"symbol": "BWP", "name": "Botswanan Pula", "symbol_native": "P", "decimal_digits": 2, "rounding": 0,
                "code": "BWP", "name_plural": "Botswanan pulas"},
        "BYN": {"symbol": "Br", "name": "Belarusian ruble", "symbol_native": "Br", "decimal_digits": 2, "rounding": 0,
                "code": "BYN", "name_plural": "Belarusian rubles"},
        "BYR": {"symbol": "BYR", "name": "Belarusian Ruble", "symbol_native": "BYR", "decimal_digits": 0, "rounding": 0,
                "code": "BYR", "name_plural": "Belarusian rubles"},
        "BZD": {"symbol": "BZ$", "name": "Belize Dollar", "symbol_native": "$", "decimal_digits": 2, "rounding": 0,
                "code": "BZD", "name_plural": "Belize dollars"},
        "CAD": {"symbol": "CA$", "name": "Canadian Dollar", "symbol_native": "$", "decimal_digits": 2, "rounding": 0,
                "code": "CAD", "name_plural": "Canadian dollars"},
        "CDF": {"symbol": "CDF", "name": "Congolese Franc", "symbol_native": "FrCD", "decimal_digits": 2, "rounding": 0,
                "code": "CDF", "name_plural": "Congolese francs"},
        "CHF": {"symbol": "CHF", "name": "Swiss Franc", "symbol_native": "CHF", "decimal_digits": 2, "rounding": 0,
                "code": "CHF", "name_plural": "Swiss francs"},
        "CLF": {"symbol": "UF", "name": "Unidad de Fomento", "symbol_native": "UF", "decimal_digits": 2, "rounding": 0,
                "code": "CLF", "name_plural": "Unidad de Fomentos"},
        "CLP": {"symbol": "CL$", "name": "Chilean Peso", "symbol_native": "$", "decimal_digits": 0, "rounding": 0,
                "code": "CLP", "name_plural": "Chilean pesos"},
        "CNY": {"symbol": "CN\xc2\xa5", "name": "Chinese Yuan", "symbol_native": "CN\xc2\xa5", "decimal_digits": 2,
                "rounding": 0, "code": "CNY", "name_plural": "Chinese yuan"},
        "COP": {"symbol": "CO$", "name": "Coombian Peso", "symbol_native": "$", "decimal_digits": 0, "rounding": 0,
                "code": "COP", "name_plural": "Colombian pesos"},
        "CRC": {"symbol": "\xe2\x82\xa1", "name": "Costa Rican Col\xc3\xb3n", "symbol_native": "\xe2\x82\xa1",
                "decimal_digits": 0, "rounding": 0, "code": "CRC", "name_plural": "Costa Rican col\xc3\xb3ns"},
        "CUC": {"symbol": "CUC$", "name": "Cuban Convertible Peso", "symbol_native": "$", "decimal_digits": 2,
                "rounding": 0, "code": "CUC", "icon_name": "cuc", "name_plural": "Cuban Convertible Peso"},
        "CUP": {"symbol": "$MN", "name": "Cuban Peso", "symbol_native": "$", "decimal_digits": 2, "rounding": 0,
                "code": "CUP", "icon_name": "cup", "name_plural": "Cuban Peso"},
        "CVE": {"symbol": "CV$", "name": "Cape Verdean Escudo", "symbol_native": "CV$", "decimal_digits": 2,
                "rounding": 0, "code": "CVE", "name_plural": "Cape Verdean escudos"},
        "CZK": {"symbol": "K\xc4\x8d", "name": "Czech Republic Koruna", "symbol_native": "K\xc4\x8d",
                "decimal_digits": 2, "rounding": 0, "code": "CZK", "name_plural": "Czech Republic korunas"},
        "DJF": {"symbol": "Fdj", "name": "Djiboutian Franc", "symbol_native": "Fdj", "decimal_digits": 0, "rounding": 0,
                "code": "DJF", "name_plural": "Djiboutian francs"},
        "DKK": {"symbol": "Dkr", "name": "Danish Krone", "symbol_native": "kr", "decimal_digits": 2, "rounding": 0,
                "code": "DKK", "name_plural": "Danish kroner"},
        "DOP": {"symbol": "RD$", "name": "Dominican Peso", "symbol_native": "RD$", "decimal_digits": 2, "rounding": 0,
                "code": "DOP", "name_plural": "Dominican pesos"},
        "DZD": {"symbol": "DA", "name": "Algerian Dinar", "symbol_native": "\xd8\xaf.\xd8\xac.\xe2\x80\x8f",
                "decimal_digits": 2, "rounding": 0, "code": "DZD", "name_plural": "Algerian dinars"},
        "EGP": {"symbol": "EGP", "name": "Egyptian Pound", "symbol_native": "\xd8\xac.\xd9\x85.\xe2\x80\x8f",
                "decimal_digits": 2, "rounding": 0, "code": "EGP", "name_plural": "Egyptian pounds"},
        "ERN": {"symbol": "Nfk", "name": "Eritrean Nakfa", "symbol_native": "Nfk", "decimal_digits": 2, "rounding": 0,
                "code": "ERN", "name_plural": "Eritrean nakfas"},
        "ETB": {"symbol": "Br", "name": "Ethiopian Birr", "symbol_native": "Br", "decimal_digits": 2, "rounding": 0,
                "code": "ETB", "name_plural": "Ethiopian birrs"},
        "EUR": {"symbol": "\xe2\x82\xac", "name": "Euro", "symbol_native": "\xe2\x82\xac", "decimal_digits": 2,
                "rounding": 0, "code": "EUR", "name_plural": "Euros"},
        "FJD": {"symbol": "FJ$", "name": "Fijian Dollar", "symbol_native": "$", "decimal_digits": 2, "rounding": 0,
                "code": "FJD", "icon_name": "fjd", "name_plural": "Fijian Dollar"},
        "FKP": {"symbol": "FK\xc2\xa3", "name": "Falkland Islands Pound", "symbol_native": "\xc2\xa3",
                "decimal_digits": 2, "rounding": 0, "code": "FKP", "icon_name": "fkp",
                "name_plural": "Falkland Islands Pound"},
        "GBP": {"symbol": "\xc2\xa3", "name": "British Pound Sterling", "symbol_native": "\xc2\xa3",
                "decimal_digits": 2, "rounding": 0, "code": "GBP", "name_plural": "British pounds sterling"},
        "GEL": {"symbol": "GEL", "name": "Georgian Lari", "symbol_native": "GEL", "decimal_digits": 2, "rounding": 0,
                "code": "GEL", "name_plural": "Georgian laris"},
        "GGP": {"symbol": "\xc2\xa3", "name": "Guernsey pound", "symbol_native": "\xc2\xa3", "decimal_digits": 2,
                "rounding": 0, "code": "GGP", "name_plural": "Guernsey pounds"},
        "GHS": {"symbol": "GH\xe2\x82\xb5", "name": "Ghanaian Cedi", "symbol_native": "GH\xe2\x82\xb5",
                "decimal_digits": 2, "rounding": 0, "code": "GHS", "name_plural": "Ghanaian cedis"},
        "GIP": {"symbol": "\xc2\xa3", "name": "Gibraltar Pound", "symbol_native": "\xc2\xa3", "decimal_digits": 2,
                "rounding": 0, "code": "GIP", "icon_name": "gip", "name_plural": "Gibraltar Pounds"},
        "GMD": {"symbol": "D", "name": "Gambian Dalasi", "symbol_native": "D", "decimal_digits": 2, "rounding": 0,
                "code": "GMD", "icon_name": "gmd", "name_plural": "Gambian Dalasi"},
        "GNF": {"symbol": "FG", "name": "Guinean Franc", "symbol_native": "FG", "decimal_digits": 0, "rounding": 0,
                "code": "GNF", "name_plural": "Guinean francs"},
        "GTQ": {"symbol": "GTQ", "name": "Guatemalan Quetzal", "symbol_native": "Q", "decimal_digits": 2, "rounding": 0,
                "code": "GTQ", "name_plural": "Guatemalan quetzals"},
        "GYD": {"symbol": "G$", "name": "Guyanaese Dollar", "symbol_native": "$", "decimal_digits": 2, "rounding": 0,
                "code": "GYD", "icon_name": "gyd", "name_plural": "Guyanaese Dollar"},
        "HKD": {"symbol": "HK$", "name": "Hong Kong Dollar", "symbol_native": "$", "decimal_digits": 2, "rounding": 0,
                "code": "HKD", "name_plural": "Hong Kong dollars"},
        "HNL": {"symbol": "HNL", "name": "Honduran Lempira", "symbol_native": "L", "decimal_digits": 2, "rounding": 0,
                "code": "HNL", "name_plural": "Honduran lempiras"},
        "HRK": {"symbol": "kn", "name": "Croatian Kuna", "symbol_native": "kn", "decimal_digits": 2, "rounding": 0,
                "code": "HRK", "name_plural": "Croatian kunas"},
        "HTG": {"symbol": "G", "name": "Haitian Gourde", "symbol_native": "G", "decimal_digits": 2, "rounding": 0,
                "code": "HTG", "icon_name": "htg", "name_plural": "Haitian Gourde"},
        "HUF": {"symbol": "Ft", "name": "Hungarian Forint", "symbol_native": "Ft", "decimal_digits": 0, "rounding": 0,
                "code": "HUF", "name_plural": "Hungarian forints"},
        "IDR": {"symbol": "Rp", "name": "Indonesian Rupiah", "symbol_native": "Rp", "decimal_digits": 0, "rounding": 0,
                "code": "IDR", "name_plural": "Indonesian rupiahs"},
        "ILS": {"symbol": "\xe2\x82\xaa", "name": "Israeli New Sheqel", "symbol_native": "\xe2\x82\xaa",
                "decimal_digits": 2, "rounding": 0, "code": "ILS", "name_plural": "Israeli new sheqels"},
        "IMP": {"symbol": "\xc2\xa3", "name": "Manx pound", "symbol_native": "\xc2\xa3", "decimal_digits": 2,
                "rounding": 0, "code": "IMP", "name_plural": "Manx pounds"},
        "INR": {"symbol": "Rs", "name": "Indian Rupee", "symbol_native": "\xe0\xa6\x9f\xe0\xa6\x95\xe0\xa6\xbe",
                "decimal_digits": 2, "rounding": 0, "code": "INR", "name_plural": "Indian rupees"},
        "IQD": {"symbol": "IQD", "name": "Iraqi Dinar", "symbol_native": "\xd8\xaf.\xd8\xb9.\xe2\x80\x8f",
                "decimal_digits": 0, "rounding": 0, "code": "IQD", "name_plural": "Iraqi dinars"},
        "IRR": {"symbol": "IRR", "name": "Iranian Rial", "symbol_native": "\xef\xb7\xbc", "decimal_digits": 0,
                "rounding": 0, "code": "IRR", "name_plural": "Iranian rials"},
        "ISK": {"symbol": "Ikr", "name": "Icelandic Kr\xc3\xb3na", "symbol_native": "kr", "decimal_digits": 0,
                "rounding": 0, "code": "ISK", "name_plural": "Icelandic kr\xc3\xb3nur"},
        "JEP": {"symbol": "\xc2\xa3", "name": "Jersey pound", "symbol_native": "\xc2\xa3", "decimal_digits": 2,
                "rounding": 0, "code": "JEP", "name_plural": "Jersey pound"},
        "JMD": {"symbol": "J$", "name": "Jamaican Dollar", "symbol_native": "$", "decimal_digits": 2, "rounding": 0,
                "code": "JMD", "name_plural": "Jamaican dollars"},
        "JOD": {"symbol": "JD", "name": "Jordanian Dinar", "symbol_native": "\xd8\xaf.\xd8\xa3.\xe2\x80\x8f",
                "decimal_digits": 3, "rounding": 0, "code": "JOD", "name_plural": "Jordanian dinars"},
        "JPY": {"symbol": "\xc2\xa5", "name": "Japanese Yen", "symbol_native": "\xef\xbf\xa5", "decimal_digits": 0,
                "rounding": 0, "code": "JPY", "name_plural": "Japanese yen"},
        "KES": {"symbol": "Ksh", "name": "Kenyan Shilling", "symbol_native": "Ksh", "decimal_digits": 2, "rounding": 0,
                "code": "KES", "name_plural": "Kenyan shillings"},
        "KGS": {"symbol": "KGS", "name": "Kyrgystani Som", "symbol_native": "KGS", "decimal_digits": 2, "rounding": 0,
                "code": "KGS", "icon_name": "kgs", "name_plural": "Kyrgystani Som"},
        "KHR": {"symbol": "KHR", "name": "Cambodian Riel", "symbol_native": "\xe1\x9f\x9b", "decimal_digits": 2,
                "rounding": 0, "code": "KHR", "name_plural": "Cambodian riels"},
        "KMF": {"symbol": "CF", "name": "Comorian Franc", "symbol_native": "FC", "decimal_digits": 0, "rounding": 0,
                "code": "KMF", "name_plural": "Comorian francs"},
        "KPW": {"symbol": "\xe2\x82\xa9", "name": "North Korean Won", "symbol_native": "\xe2\x82\xa9",
                "decimal_digits": 2, "rounding": 0, "code": "KPW", "icon_name": "kpw",
                "name_plural": "North Korean Won"},
        "KRW": {"symbol": "\xe2\x82\xa9", "name": "South Korean Won", "symbol_native": "\xe2\x82\xa9",
                "decimal_digits": 0, "rounding": 0, "code": "KRW", "name_plural": "South Korean won"},
        "KWD": {"symbol": "KD", "name": "Kuwaiti Dinar", "symbol_native": "\xd8\xaf.\xd9\x83.\xe2\x80\x8f",
                "decimal_digits": 3, "rounding": 0, "code": "KWD", "name_plural": "Kuwaiti dinars"},
        "KYD": {"symbol": "CI$", "name": "Cayman Islands Dollar", "symbol_native": "$\xe2\x80\x8f", "decimal_digits": 2,
                "rounding": 0, "code": "KYD", "icon_name": "kyd", "name_plural": "Cayman Islands Dollar"},
        "KZT": {"symbol": "KZT", "name": "Kazakhstani Tenge", "symbol_native": "\xd1\x82\xd2\xa3\xd0\xb3.",
                "decimal_digits": 2, "rounding": 0, "code": "KZT", "name_plural": "Kazakhstani tenges"},
        "LAK": {"symbol": "\xe2\x82\xadN", "name": "Laotian Kip",
                "symbol_native": "\xe2\x82\xad\xe2\x80\x8f\xe2\x80\x8f", "decimal_digits": 0, "rounding": 0,
                "code": "LAK", "name_plural": "Laotian Kip"},
        "LBP": {"symbol": "LB\xc2\xa3", "name": "Lebanese Pound", "symbol_native": "\xd9\x84.\xd9\x84.\xe2\x80\x8f",
                "decimal_digits": 0, "rounding": 0, "code": "LBP", "name_plural": "Lebanese pounds"},
        "LKR": {"symbol": "SLRs", "name": "Sri Lankan Rupee", "symbol_native": "SL Re", "decimal_digits": 2,
                "rounding": 0, "code": "LKR", "name_plural": "Sri Lankan rupees"},
        "LRD": {"symbol": "LD$", "name": "Liberian Dollar", "symbol_native": "L$", "decimal_digits": 2, "rounding": 0,
                "code": "LRD", "icon_name": "lrd", "name_plural": "Liberian Dollar"},
        "LSL": {"symbol": "L", "name": "Lesotho Loti", "symbol_native": "M", "decimal_digits": 2, "rounding": 0,
                "code": "LSL", "icon_name": "lsl", "name_plural": "Lesotho Loti"},
        "LTL": {"symbol": "Lt", "name": "Lithuanian Litas", "symbol_native": "Lt", "decimal_digits": 2, "rounding": 0,
                "code": "LTL", "name_plural": "Lithuanian litai"},
        "LVL": {"symbol": "Ls", "name": "Latvian Lats", "symbol_native": "Ls", "decimal_digits": 2, "rounding": 0,
                "code": "LVL", "name_plural": "Latvian lati"},
        "LYD": {"symbol": "LD", "name": "Libyan Dinar", "symbol_native": "\xd8\xaf.\xd9\x84.\xe2\x80\x8f",
                "decimal_digits": 3, "rounding": 0, "code": "LYD", "name_plural": "Libyan dinars"},
        "MAD": {"symbol": "MAD", "name": "Moroccan Dirham", "symbol_native": "\xd8\xaf.\xd9\x85.\xe2\x80\x8f",
                "decimal_digits": 2, "rounding": 0, "code": "MAD", "name_plural": "Moroccan dirhams"},
        "MDL": {"symbol": "MDL", "name": "Moldovan Leu", "symbol_native": "MDL", "decimal_digits": 2, "rounding": 0,
                "code": "MDL", "name_plural": "Moldovan lei"},
        "MGA": {"symbol": "MGA", "name": "Malagasy Ariary", "symbol_native": "MGA", "decimal_digits": 0, "rounding": 0,
                "code": "MGA", "name_plural": "Malagasy Ariaries"},
        "MKD": {"symbol": "MKD", "name": "Macedonian Denar", "symbol_native": "MKD", "decimal_digits": 2, "rounding": 0,
                "code": "MKD", "name_plural": "Macedonian denari"},
        "MMK": {"symbol": "MMK", "name": "Myanma Kyat", "symbol_native": "K", "decimal_digits": 0, "rounding": 0,
                "code": "MMK", "name_plural": "Myanma kyats"},
        "MNT": {"symbol": "\xe2\x82\xae", "name": "Mongolian Tugrik", "symbol_native": "\xe2\x82\xae",
                "decimal_digits": 2, "rounding": 0, "code": "MNT", "icon_name": "mnt",
                "name_plural": "Mongolian Tugrik"},
        "MOP": {"symbol": "MOP$", "name": "Macanese Pataca", "symbol_native": "MOP$", "decimal_digits": 2,
                "rounding": 0, "code": "MOP", "name_plural": "Macanese patacas"},
        "MRO": {"symbol": "UM", "name": "Mauritanian ouguiya", "symbol_native": "UM", "decimal_digits": 2,
                "rounding": 0, "code": "MRO", "name_plural": "Mauritanian ouguiyas"},
        "MUR": {"symbol": "MURs", "name": "Mauritian Rupee", "symbol_native": "MURs", "decimal_digits": 0,
                "rounding": 0, "code": "MUR", "name_plural": "Mauritian rupees"},
        "MVR": {"symbol": "MRf", "name": "Maldivian Rufiyaa", "symbol_native": "Rf", "decimal_digits": 2, "rounding": 0,
                "code": "MVR", "name_plural": "Maldivian Rufiyaa"},
        "MWK": {"symbol": "MK", "name": "Malawian Kwacha", "symbol_native": "MK", "decimal_digits": 2, "rounding": 0,
                "code": "MWK", "icon_name": "mwk", "name_plural": "Malawian Kwacha"},
        "MXN": {"symbol": "MX$", "name": "Mexican Peso", "symbol_native": "$", "decimal_digits": 2, "rounding": 0,
                "code": "MXN", "name_plural": "Mexican pesos"},
        "MYR": {"symbol": "RM", "name": "Malaysian Ringgit", "symbol_native": "RM", "decimal_digits": 2, "rounding": 0,
                "code": "MYR", "name_plural": "Malaysian ringgits"},
        "MZN": {"symbol": "MTn", "name": "Mozambican Metical", "symbol_native": "MTn", "decimal_digits": 2,
                "rounding": 0, "code": "MZN", "name_plural": "Mozambican meticals"},
        "NAD": {"symbol": "N$", "name": "Namibian Dollar", "symbol_native": "N$", "decimal_digits": 2, "rounding": 0,
                "code": "NAD", "name_plural": "Namibian dollars"},
        "NGN": {"symbol": "\xe2\x82\xa6", "name": "Nigerian Naira", "symbol_native": "\xe2\x82\xa6",
                "decimal_digits": 2, "rounding": 0, "code": "NGN", "name_plural": "Nigerian nairas"},
        "NIO": {"symbol": "C$", "name": "Nicaraguan C\xc3\xb3rdoba", "symbol_native": "C$", "decimal_digits": 2,
                "rounding": 0, "code": "NIO", "name_plural": "Nicaraguan c\xc3\xb3rdobas"},
        "NOK": {"symbol": "Nkr", "name": "Norwegian Krone", "symbol_native": "kr", "decimal_digits": 2, "rounding": 0,
                "code": "NOK", "name_plural": "Norwegian kroner"},
        "NPR": {"symbol": "NPRs", "name": "Nepalese Rupee",
                "symbol_native": "\xe0\xa4\xa8\xe0\xa5\x87\xe0\xa4\xb0\xe0\xa5\x82", "decimal_digits": 2, "rounding": 0,
                "code": "NPR", "name_plural": "Nepalese rupees"},
        "NZD": {"symbol": "NZ$", "name": "New Zealand Dollar", "symbol_native": "$", "decimal_digits": 2, "rounding": 0,
                "code": "NZD", "name_plural": "New Zealand dollars"},
        "OMR": {"symbol": "OMR", "name": "Omani Rial", "symbol_native": "\xd8\xb1.\xd8\xb9.\xe2\x80\x8f",
                "decimal_digits": 3, "rounding": 0, "code": "OMR", "name_plural": "Omani rials"},
        "PAB": {"symbol": "B\\/.", "name": "Panamanian Balboa", "symbol_native": "B\\/.", "decimal_digits": 2,
                "rounding": 0, "code": "PAB", "name_plural": "Panamanian balboas"},
        "PEN": {"symbol": "S\\/.", "name": "Peruvian Nuevo Sol", "symbol_native": "S\\/.", "decimal_digits": 2,
                "rounding": 0, "code": "PEN", "name_plural": "Peruvian nuevos soles"},
        "PGK": {"symbol": "K", "name": "Papua New Guinean Kina", "symbol_native": "K", "decimal_digits": 2,
                "rounding": 0, "code": "PGK", "icon_name": "pgk", "name_plural": "Papua New Guinean Kina"},
        "PHP": {"symbol": "\xe2\x82\xb1", "name": "Philippine Peso", "symbol_native": "\xe2\x82\xb1",
                "decimal_digits": 2, "rounding": 0, "code": "PHP", "name_plural": "Philippine pesos"},
        "PKR": {"symbol": "PKRs", "name": "Pakistani Rupee", "symbol_native": "\xe2\x82\xa8", "decimal_digits": 0,
                "rounding": 0, "code": "PKR", "name_plural": "Pakistani rupees"},
        "PLN": {"symbol": "z\xc5\x82", "name": "Polish Zloty", "symbol_native": "z\xc5\x82", "decimal_digits": 2,
                "rounding": 0, "code": "PLN", "name_plural": "Polish zlotys"},
        "PYG": {"symbol": "\xe2\x82\xb2", "name": "Paraguayan Guarani", "symbol_native": "\xe2\x82\xb2",
                "decimal_digits": 0, "rounding": 0, "code": "PYG", "name_plural": "Paraguayan guaranis"},
        "QAR": {"symbol": "QR", "name": "Qatari Rial", "symbol_native": "\xd8\xb1.\xd9\x82.\xe2\x80\x8f",
                "decimal_digits": 2, "rounding": 0, "code": "QAR", "name_plural": "Qatari rials"},
        "RON": {"symbol": "RON", "name": "Romanian Leu", "symbol_native": "RON", "decimal_digits": 2, "rounding": 0,
                "code": "RON", "name_plural": "Romanian lei"},
        "RSD": {"symbol": "din.", "name": "Serbian Dinar", "symbol_native": "\xd0\xb4\xd0\xb8\xd0\xbd.",
                "decimal_digits": 0, "rounding": 0, "code": "RSD", "name_plural": "Serbian dinars"},
        "RUB": {"symbol": "RUB", "name": "Russian Ruble", "symbol_native": "\xd1\x80\xd1\x83\xd0\xb1.",
                "decimal_digits": 2, "rounding": 0, "code": "RUB", "name_plural": "Russian rubles"},
        "RWF": {"symbol": "RWF", "name": "Rwandan Franc", "symbol_native": "FR", "decimal_digits": 0, "rounding": 0,
                "code": "RWF", "name_plural": "Rwandan francs"},
        "SAR": {"symbol": "SR", "name": "Saudi Riyal", "symbol_native": "\xd8\xb1.\xd8\xb3.\xe2\x80\x8f",
                "decimal_digits": 2, "rounding": 0, "code": "SAR", "name_plural": "Saudi riyals"},
        "SBD": {"symbol": "SI$", "name": "Solomon Islands Dollar", "symbol_native": "$", "decimal_digits": 2,
                "rounding": 0, "code": "SBD", "icon_name": "sbd", "name_plural": "Solomon Islands Dollars"},
        "SCR": {"symbol": "SRe", "name": "Seychellois Rupee", "symbol_native": "SR", "decimal_digits": 2, "rounding": 0,
                "code": "SCR", "icon_name": "scr", "name_plural": "Seychellois Rupees"},
        "SDG": {"symbol": "SDG", "name": "Sudanese Pound", "symbol_native": "SDG", "decimal_digits": 2, "rounding": 0,
                "code": "SDG", "name_plural": "Sudanese pounds"},
        "SEK": {"symbol": "Skr", "name": "Swedish Krona", "symbol_native": "kr", "decimal_digits": 2, "rounding": 0,
                "code": "SEK", "name_plural": "Swedish kronor"},
        "SGD": {"symbol": "S$", "name": "Singapore Dollar", "symbol_native": "$", "decimal_digits": 2, "rounding": 0,
                "code": "SGD", "name_plural": "Singapore dollars"},
        "SHP": {"symbol": "\xc2\xa3", "name": "Saint Helena Pound", "symbol_native": "\xc2\xa3", "decimal_digits": 2,
                "rounding": 0, "code": "SHP", "icon_name": "shp", "name_plural": "Saint Helena Pounds"},
        "SLL": {"symbol": "Le", "name": "Sierra Leonean Leone", "symbol_native": "Le", "decimal_digits": 2,
                "rounding": 0, "code": "SLL", "icon_name": "sll", "name_plural": "Sierra Leonean Leone"},
        "SOS": {"symbol": "Ssh", "name": "Somali Shilling", "symbol_native": "Ssh", "decimal_digits": 0, "rounding": 0,
                "code": "SOS", "name_plural": "Somali shillings"},
        "SRD": {"symbol": "$", "name": "Surinamese Dollar", "symbol_native": "$", "decimal_digits": 2, "rounding": 0,
                "code": "SRD", "icon_name": "srd", "name_plural": "Surinamese Dollar"},
        "STD": {"symbol": "Db", "name": "S\xc3\xa3o Tom\xc3\xa9 and Pr\xc3\xadncipe dobra", "symbol_native": "Db",
                "decimal_digits": 2, "rounding": 0, "code": "STD",
                "name_plural": "S\xc3\xa3o Tom\xc3\xa9 and Pr\xc3\xadncipe dobras"},
        "SVC": {"symbol": "\xe2\x82\xa1", "name": "Salvadoran Col\xc3\xb3n", "symbol_native": "\xe2\x82\xa1",
                "decimal_digits": 2, "rounding": 0, "code": "SVC", "icon_name": "svc",
                "name_plural": "Salvadoran Col\xc3\xb3n"},
        "SYP": {"symbol": "SY\xc2\xa3", "name": "Syrian Pound", "symbol_native": "\xd9\x84.\xd8\xb3.\xe2\x80\x8f",
                "decimal_digits": 0, "rounding": 0, "code": "SYP", "name_plural": "Syrian pounds"},
        "SZL": {"symbol": "L", "name": "Swazi Lilangeni", "symbol_native": "E\xe2\x80\x8f", "decimal_digits": 2,
                "rounding": 0, "code": "SZL", "icon_name": "szl", "name_plural": "Swazi Lilangeni"},
        "THB": {"symbol": "\xe0\xb8\xbf", "name": "Thai Baht", "symbol_native": "\xe0\xb8\xbf", "decimal_digits": 2,
                "rounding": 0, "code": "THB", "name_plural": "Thai baht"},
        "TJS": {"symbol": "TJS", "name": "Tajikistani Somoni", "symbol_native": "TJS", "decimal_digits": 2,
                "rounding": 0, "code": "TJS", "icon_name": "tjs", "name_plural": "Tajikistani Somoni"},
        "TMT": {"symbol": "T", "name": "Turkmenistani Manat", "symbol_native": "T\xe2\x80\x8f", "decimal_digits": 2,
                "rounding": 0, "code": "TMT", "icon_name": "tmt", "name_plural": "Turkmenistani Manat"},
        "TND": {"symbol": "DT", "name": "Tunisian Dinar", "symbol_native": "\xd8\xaf.\xd8\xaa.\xe2\x80\x8f",
                "decimal_digits": 3, "rounding": 0, "code": "TND", "name_plural": "Tunisian dinars"},
        "TOP": {"symbol": "T$", "name": "Tongan Pa\xca\xbbanga", "symbol_native": "T$", "decimal_digits": 2,
                "rounding": 0, "code": "TOP", "name_plural": "Tongan pa\xca\xbbanga"},
        "TRY": {"symbol": "TL", "name": "Turkish Lira", "symbol_native": "TL", "decimal_digits": 2, "rounding": 0,
                "code": "TRY", "name_plural": "Turkish Lira"},
        "TTD": {"symbol": "TT$", "name": "Trinidad and Tobago Dollar", "symbol_native": "$", "decimal_digits": 2,
                "rounding": 0, "code": "TTD", "name_plural": "Trinidad and Tobago dollars"},
        "TWD": {"symbol": "NT$", "name": "New Taiwan Dollar", "symbol_native": "NT$", "decimal_digits": 2,
                "rounding": 0, "code": "TWD", "name_plural": "New Taiwan dollars"},
        "TZS": {"symbol": "TSh", "name": "Tanzanian Shilling", "symbol_native": "TSh", "decimal_digits": 0,
                "rounding": 0, "code": "TZS", "name_plural": "Tanzanian shillings"},
        "UAH": {"symbol": "\xe2\x82\xb4", "name": "Ukrainian Hryvnia", "symbol_native": "\xe2\x82\xb4",
                "decimal_digits": 2, "rounding": 0, "code": "UAH", "name_plural": "Ukrainian hryvnias"},
        "UGX": {"symbol": "USh", "name": "Ugandan Shilling", "symbol_native": "USh", "decimal_digits": 0, "rounding": 0,
                "code": "UGX", "name_plural": "Ugandan shillings"},
        "USD": {"symbol": "$", "name": "US Dollar", "symbol_native": "$", "decimal_digits": 2, "rounding": 0,
                "code": "USD", "name_plural": "US dollars"},
        "UYU": {"symbol": "$U", "name": "Uruguayan Peso", "symbol_native": "$", "decimal_digits": 2, "rounding": 0,
                "code": "UYU", "name_plural": "Uruguayan pesos"},
        "UZS": {"symbol": "UZS", "name": "Uzbekistan Som", "symbol_native": "UZS", "decimal_digits": 0, "rounding": 0,
                "code": "UZS", "name_plural": "Uzbekistan som"},
        "VEF": {"symbol": "Bs.F.", "name": "Venezuelan Bol\xc3\xadvar", "symbol_native": "Bs.F.", "decimal_digits": 2,
                "rounding": 0, "code": "VEF", "name_plural": "Venezuelan bol\xc3\xadvars"},
        "VND": {"symbol": "\xe2\x82\xab", "name": "Vietnamese Dong", "symbol_native": "\xe2\x82\xab",
                "decimal_digits": 0, "rounding": 0, "code": "VND", "name_plural": "Vietnamese dong"},
        "VUV": {"symbol": "VUV", "name": "Vanuatu Vatu", "symbol_native": "VT", "decimal_digits": 0, "rounding": 0,
                "code": "VUV", "icon_name": "vuv", "name_plural": "Vanuatu Vatu"},
        "WST": {"symbol": "WS$", "name": "Samoan Tala", "symbol_native": "T", "decimal_digits": 2, "rounding": 0,
                "code": "WST", "icon_name": "wst", "name_plural": "Samoan Tala"},
        "XAF": {"symbol": "FCFA", "name": "CFA Franc BEAC", "symbol_native": "FCFA", "decimal_digits": 0, "rounding": 0,
                "code": "XAF", "name_plural": "CFA francs BEAC"},
        "XAG": {"symbol": "XAG", "name": "Silver Ounce", "symbol_native": "XAG", "decimal_digits": 2, "rounding": 0,
                "code": "XAG", "name_plural": "Silver Ounces"},
        "XAU": {"symbol": "XAU", "name": "Gold Ounce", "symbol_native": "XAU", "decimal_digits": 2, "rounding": 0,
                "code": "XAU", "name_plural": "Gold Ounces"},
        "XCD": {"symbol": "EC$", "name": "East Caribbean Dollar", "symbol_native": "$", "decimal_digits": 2,
                "rounding": 0, "code": "XCD", "icon_name": "xcd", "name_plural": "East Caribbean Dollars"},
        "XDR": {"symbol": "SDR", "name": "Special drawing rights", "symbol_native": "SDR", "decimal_digits": 2,
                "rounding": 0, "code": "XDR", "name_plural": "Special drawing rights"},
        "XOF": {"symbol": "CFA", "name": "CFA Franc BCEAO", "symbol_native": "CFA", "decimal_digits": 0, "rounding": 0,
                "code": "XOF", "name_plural": "CFA francs BCEAO"},
        "XPF": {"symbol": "CFP", "name": "CFP Franc", "symbol_native": "CFP", "decimal_digits": 0, "rounding": 0,
                "code": "XPF", "icon_name": "xpf", "name_plural": "CFP francs"},
        "YER": {"symbol": "YR", "name": "Yemeni Rial", "symbol_native": "\xd8\xb1.\xd9\x8a.\xe2\x80\x8f",
                "decimal_digits": 0, "rounding": 0, "code": "YER", "name_plural": "Yemeni rials"},
        "ZAR": {"symbol": "R", "name": "South African Rand", "symbol_native": "R", "decimal_digits": 2, "rounding": 0,
                "code": "ZAR", "name_plural": "South African rand"},
        "ZMK": {"symbol": "ZK", "name": "Zambian Kwacha", "symbol_native": "ZK", "decimal_digits": 0, "rounding": 0,
                "code": "ZMK", "name_plural": "Zambian kwachas"},
        "ZMW": {"symbol": "ZK", "name": "Zambian Kwacha", "symbol_native": "ZK", "decimal_digits": 0, "rounding": 0,
                "code": "ZMW", "name_plural": "Zambian kwachas"},
        "ZWL": {"symbol": "ZWL", "name": "Zimbabwean dollar", "symbol_native": "$", "decimal_digits": 2, "rounding": 0,
                "code": "ZWL", "name_plural": "Zimbabwean dollars"},
        "XPT": {"symbol": "XPT", "name": "Platinum Ounce", "symbol_native": "XPT", "decimal_digits": 6, "rounding": 0,
                "code": "XPT", "name_plural": "Platinum Ounces"},
        "XPD": {"symbol": "XPD", "name": "Palladium Ounce", "symbol_native": "XPD", "decimal_digits": 6, "rounding": 0,
                "code": "XPD", "name_plural": "Palladium Ounces"},
        "BTC": {"symbol": "\xe2\x82\xbf", "name": "Bitcoin", "symbol_native": "\xe2\x82\xbf", "decimal_digits": 8,
                "rounding": 0, "code": "BTC", "name_plural": "Bitcoins"},
        "ETH": {"symbol": "\xce\x9e", "name": "Ethereum", "symbol_native": "\xce\x9e", "decimal_digits": 18,
                "rounding": 0, "code": "ETH", "name_plural": "Ethereum"},
        "BNB": {"symbol": "BNB", "name": "Binance", "symbol_native": "BNB", "decimal_digits": 8, "rounding": 0,
                "code": "BNB", "name_plural": "Binance"},
        "XRP": {"symbol": "XRP", "name": "Ripple", "symbol_native": "XRP", "decimal_digits": 6, "rounding": 0,
                "code": "XRP", "name_plural": "Ripple"},
        "SOL": {"symbol": "SOL", "name": "Solana", "symbol_native": "SOL", "decimal_digits": 9, "rounding": 0,
                "code": "SOL", "name_plural": "Solana"},
        "DOT": {"symbol": "DOT", "name": "Polkadot", "symbol_native": "DOT", "decimal_digits": 10, "rounding": 0,
                "code": "DOT", "name_plural": "Polkadot"},
        "AVAX": {"symbol": "AVAX", "name": "Avalanche", "symbol_native": "AVAX", "decimal_digits": 18, "rounding": 0,
                 "code": "AVAX", "name_plural": "Avalanche"},
        "MATIC": {"symbol": "MATIC", "name": "Matic Token", "symbol_native": "MATIC", "decimal_digits": 18,
                  "rounding": 0, "code": "MATIC", "name_plural": "Matic Tokens"},
        "LTC": {"symbol": "\xc5\x81", "name": "Litecoin", "symbol_native": "\xc5\x81", "decimal_digits": 8,
                "rounding": 0, "code": "LTC", "name_plural": "Litecoins"},
        "ADA": {"symbol": "ADA", "name": "Cardano", "symbol_native": "ADA", "decimal_digits": 6, "rounding": 0,
                "code": "ADA", "name_plural": "Cardanos"},
        "USDT": None,
        "USDC": None,
        "DAI": None,
        "BUSD": None,
        "ARB": None,
        "OP": None
              }
     }

pair_info = \
    [
        {'symbol': '$', 'name': 'US Dollar', 'symbol_native': '$', 'decimal_digits': 2, 'rounding': 0,
         'code': 'USD', 'name_plural': 'US dollars'},
        {'symbol': 'RUB', 'name': 'Russian Ruble', 'symbol_native': 'руб.', 'decimal_digits': 2, 'rounding': 0,
         'code': 'RUB', 'name_plural': 'Russian rubles'},
        10.0
    ]
